# Site settings
title: Hyein's learn space
description: "이곳은 제가 공부한것들을 올려놓는 곳입니다."
baseurl: "" # the subpath of your site, e.g. /blog
url: https://Hye-inLee.github.io/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
author:
  username: <Lee> <Hyein>
  user_title: <Software Engineer>
  email: <leehyeine@gmail.com>
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum


exclude: ['package.json', 'src' , 'node_modules']
